clc

addpath("classes/");

addpath("data_generation/");

gen_residue_properties;

addpath("functions_and_scripts/");

addpath("pdb_data/");

addpath("methods_paper_figures//");

addpath("sidechain_dist//");

load("helix_indeces.mat");

pdb_filepaths = [ ...
    "talin_pdb_files/R1.pdb",...
    "talin_pdb_files/R2.pdb",...
    "talin_pdb_files/R3.pdb",...
    "talin_pdb_files/R4.pdb",...
    "talin_pdb_files/R5.pdb",...
    "talin_pdb_files/R6.pdb",...
    "talin_pdb_files/R7R8.pdb",...
    "talin_pdb_files/R7R8.pdb",...
    "talin_pdb_files/R9.pdb",...
    "talin_pdb_files/R10.pdb",...
    "talin_pdb_files/R11.pdb",...
    "talin_pdb_files/R12.pdb",...
    "talin_pdb_files/R13.pdb",...
    ];
